// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: jumpstart/domain/onboardings/v1/values.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Jumpstart.Domain.Onboardings.Values.V1 {

  /// <summary>Holder for reflection information generated from jumpstart/domain/onboardings/v1/values.proto</summary>
  public static partial class ValuesReflection {

    #region Descriptor
    /// <summary>File descriptor for jumpstart/domain/onboardings/v1/values.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ValuesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixqdW1wc3RhcnQvZG9tYWluL29uYm9hcmRpbmdzL3YxL3ZhbHVlcy5wcm90",
            "bxImanVtcHN0YXJ0LmRvbWFpbi5vbmJvYXJkaW5ncy52YWx1ZXMudjEidAoI",
            "QXBwcm92YWwSTgoGc3RhdHVzGAEgASgOMjYuanVtcHN0YXJ0LmRvbWFpbi5v",
            "bmJvYXJkaW5ncy52YWx1ZXMudjEuQXBwcm92YWxTdGF0dXNSBnN0YXR1cxIY",
            "Cgdjb21tZW50GAIgASgJUgdjb21tZW50IoIBCh1PbmJvYXJkRW50aXR5RXhl",
            "Y3V0aW9uT3B0aW9ucxI8Chpjb21wbGV0aW9uX3RpbWVvdXRfc2Vjb25kcxgB",
            "IAEoBFIYY29tcGxldGlvblRpbWVvdXRTZWNvbmRzEiMKDXNraXBfYXBwcm92",
            "YWwYAiABKAhSDHNraXBBcHByb3ZhbCqKAQoOQXBwcm92YWxTdGF0dXMSHwob",
            "QVBQUk9WQUxfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGwoXQVBQUk9WQUxfU1RB",
            "VFVTX1BFTkRJTkcQARIcChhBUFBST1ZBTF9TVEFUVVNfUkVKRUNURUQQAhIc",
            "ChhBUFBST1ZBTF9TVEFUVVNfQVBQUk9WRUQQAyqDAQoGRXJyb3JzEhYKEkVS",
            "Uk9SU19VTlNQRUNJRklFRBAAEhwKGEVSUk9SU19JTlZBTElEX0FSR1VNRU5U",
            "UxABEiMKH0VSUk9SU19PTkJPQVJEX0VOVElUWV9USU1FRF9PVVQQAhIeChpF",
            "UlJPUlNfU0VSVklDRV9VTkFWQUlMQUJMRRADQvYBCipjb20uanVtcHN0YXJ0",
            "LmRvbWFpbi5vbmJvYXJkaW5ncy52YWx1ZXMudjFCC1ZhbHVlc1Byb3RvUAGi",
            "AgRKRE9WqgImSnVtcHN0YXJ0LkRvbWFpbi5PbmJvYXJkaW5ncy5WYWx1ZXMu",
            "VjHKAiZKdW1wc3RhcnRcRG9tYWluXE9uYm9hcmRpbmdzXFZhbHVlc1xWMeIC",
            "Mkp1bXBzdGFydFxEb21haW5cT25ib2FyZGluZ3NcVmFsdWVzXFYxXEdQQk1l",
            "dGFkYXRh6gIqSnVtcHN0YXJ0OjpEb21haW46Ok9uYm9hcmRpbmdzOjpWYWx1",
            "ZXM6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus), typeof(global::Jumpstart.Domain.Onboardings.Values.V1.Errors), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Jumpstart.Domain.Onboardings.Values.V1.Approval), global::Jumpstart.Domain.Onboardings.Values.V1.Approval.Parser, new[]{ "Status", "Comment" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jumpstart.Domain.Onboardings.Values.V1.OnboardEntityExecutionOptions), global::Jumpstart.Domain.Onboardings.Values.V1.OnboardEntityExecutionOptions.Parser, new[]{ "CompletionTimeoutSeconds", "SkipApproval" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ApprovalStatus {
    [pbr::OriginalName("APPROVAL_STATUS_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("APPROVAL_STATUS_PENDING")] Pending = 1,
    [pbr::OriginalName("APPROVAL_STATUS_REJECTED")] Rejected = 2,
    [pbr::OriginalName("APPROVAL_STATUS_APPROVED")] Approved = 3,
  }

  public enum Errors {
    [pbr::OriginalName("ERRORS_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("ERRORS_INVALID_ARGUMENTS")] InvalidArguments = 1,
    [pbr::OriginalName("ERRORS_ONBOARD_ENTITY_TIMED_OUT")] OnboardEntityTimedOut = 2,
    [pbr::OriginalName("ERRORS_SERVICE_UNAVAILABLE")] ServiceUnavailable = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Approval : pb::IMessage<Approval>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Approval> _parser = new pb::MessageParser<Approval>(() => new Approval());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Approval> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jumpstart.Domain.Onboardings.Values.V1.ValuesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Approval() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Approval(Approval other) : this() {
      status_ = other.status_;
      comment_ = other.comment_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Approval Clone() {
      return new Approval(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus status_ = global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "comment" field.</summary>
    public const int CommentFieldNumber = 2;
    private string comment_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Comment {
      get { return comment_; }
      set {
        comment_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Approval);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Approval other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (Comment != other.Comment) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus.Unspecified) hash ^= Status.GetHashCode();
      if (Comment.Length != 0) hash ^= Comment.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (Comment.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Comment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (Comment.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Comment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Comment.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Comment);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Approval other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus.Unspecified) {
        Status = other.Status;
      }
      if (other.Comment.Length != 0) {
        Comment = other.Comment;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus) input.ReadEnum();
            break;
          }
          case 18: {
            Comment = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Jumpstart.Domain.Onboardings.Values.V1.ApprovalStatus) input.ReadEnum();
            break;
          }
          case 18: {
            Comment = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OnboardEntityExecutionOptions : pb::IMessage<OnboardEntityExecutionOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OnboardEntityExecutionOptions> _parser = new pb::MessageParser<OnboardEntityExecutionOptions>(() => new OnboardEntityExecutionOptions());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OnboardEntityExecutionOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jumpstart.Domain.Onboardings.Values.V1.ValuesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardEntityExecutionOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardEntityExecutionOptions(OnboardEntityExecutionOptions other) : this() {
      completionTimeoutSeconds_ = other.completionTimeoutSeconds_;
      skipApproval_ = other.skipApproval_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardEntityExecutionOptions Clone() {
      return new OnboardEntityExecutionOptions(this);
    }

    /// <summary>Field number for the "completion_timeout_seconds" field.</summary>
    public const int CompletionTimeoutSecondsFieldNumber = 1;
    private ulong completionTimeoutSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CompletionTimeoutSeconds {
      get { return completionTimeoutSeconds_; }
      set {
        completionTimeoutSeconds_ = value;
      }
    }

    /// <summary>Field number for the "skip_approval" field.</summary>
    public const int SkipApprovalFieldNumber = 2;
    private bool skipApproval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SkipApproval {
      get { return skipApproval_; }
      set {
        skipApproval_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OnboardEntityExecutionOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OnboardEntityExecutionOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CompletionTimeoutSeconds != other.CompletionTimeoutSeconds) return false;
      if (SkipApproval != other.SkipApproval) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CompletionTimeoutSeconds != 0UL) hash ^= CompletionTimeoutSeconds.GetHashCode();
      if (SkipApproval != false) hash ^= SkipApproval.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CompletionTimeoutSeconds != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(CompletionTimeoutSeconds);
      }
      if (SkipApproval != false) {
        output.WriteRawTag(16);
        output.WriteBool(SkipApproval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CompletionTimeoutSeconds != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(CompletionTimeoutSeconds);
      }
      if (SkipApproval != false) {
        output.WriteRawTag(16);
        output.WriteBool(SkipApproval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CompletionTimeoutSeconds != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CompletionTimeoutSeconds);
      }
      if (SkipApproval != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OnboardEntityExecutionOptions other) {
      if (other == null) {
        return;
      }
      if (other.CompletionTimeoutSeconds != 0UL) {
        CompletionTimeoutSeconds = other.CompletionTimeoutSeconds;
      }
      if (other.SkipApproval != false) {
        SkipApproval = other.SkipApproval;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CompletionTimeoutSeconds = input.ReadUInt64();
            break;
          }
          case 16: {
            SkipApproval = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CompletionTimeoutSeconds = input.ReadUInt64();
            break;
          }
          case 16: {
            SkipApproval = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
