syntax = "proto3";

import "onboardings/domain/values/v1/message.proto";

package onboardings.domain.commands.v1;

message RegisterCrmEntityRequest {
  string id = 1;
  string value = 2;
}
message RequestDeputyOwnerApprovalRequest {
  string id = 1;
  string deputy_owner_email = 2;
}
message ApproveEntityRequest {
  string comment = 1;
}
message RejectEntityRequest {
  string comment = 1;
}
message SetValueRequest {
  string value = 1;
}
message GetOnboardEntityExecutionOptionsRequest {
  onboardings.domain.values.v1.OnboardEntityExecutionOptions options = 1;
}
message GetOnboardEntityExecutionOptionsResponse {
  onboardings.domain.values.v1.OnboardEntityExecutionOptions options = 1;
}