global:
  scrape_interval: 60s
remote_write:
  - url: redacted
    basic_auth:
      username: redacted
      password: redacted
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]
