// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: onboardings/domain/queries/v2/message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Onboardings.Domain.Queries.V2 {

  /// <summary>Holder for reflection information generated from onboardings/domain/queries/v2/message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for onboardings/domain/queries/v2/message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitvbmJvYXJkaW5ncy9kb21haW4vcXVlcmllcy92Mi9tZXNzYWdlLnByb3Rv",
            "Eh1vbmJvYXJkaW5ncy5kb21haW4ucXVlcmllcy52Mhotb25ib2FyZGluZ3Mv",
            "ZG9tYWluL3dvcmtmbG93cy92Mi9tZXNzYWdlLnByb3RvGipvbmJvYXJkaW5n",
            "cy9kb21haW4vdmFsdWVzL3YxL21lc3NhZ2UucHJvdG8iIQofR2V0RW50aXR5",
            "T25ib2FyZGluZ1N0YXRlUmVxdWVzdCLWAgogR2V0RW50aXR5T25ib2FyZGlu",
            "Z1N0YXRlUmVzcG9uc2USDgoCaWQYASABKAlSAmlkEkkKBGFyZ3MYAiABKAsy",
            "NS5vbmJvYXJkaW5ncy5kb21haW4ud29ya2Zsb3dzLnYyLk9uYm9hcmRFbnRp",
            "dHlSZXF1ZXN0UgRhcmdzEkIKCGFwcHJvdmFsGAMgASgLMiYub25ib2FyZGlu",
            "Z3MuZG9tYWluLnZhbHVlcy52MS5BcHByb3ZhbFIIYXBwcm92YWwSIwoNY3Vy",
            "cmVudF92YWx1ZRgEIAEoCVIMY3VycmVudFZhbHVlEkoKH2FwcHJvdmFsX3Rp",
            "bWVfcmVtYWluaW5nX3NlY29uZHMYBSABKARIAFIcYXBwcm92YWxUaW1lUmVt",
            "YWluaW5nU2Vjb25kc4gBAUIiCiBfYXBwcm92YWxfdGltZV9yZW1haW5pbmdf",
            "c2Vjb25kc0LIAQohY29tLm9uYm9hcmRpbmdzLmRvbWFpbi5xdWVyaWVzLnYy",
            "QgxNZXNzYWdlUHJvdG9QAaICA09EUaoCHU9uYm9hcmRpbmdzLkRvbWFpbi5R",
            "dWVyaWVzLlYyygIdT25ib2FyZGluZ3NcRG9tYWluXFF1ZXJpZXNcVjLiAilP",
            "bmJvYXJkaW5nc1xEb21haW5cUXVlcmllc1xWMlxHUEJNZXRhZGF0YeoCIE9u",
            "Ym9hcmRpbmdzOjpEb21haW46OlF1ZXJpZXM6OlYyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Onboardings.Domain.Workflows.V2.MessageReflection.Descriptor, global::Onboardings.Domain.Values.V1.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Onboardings.Domain.Queries.V2.GetEntityOnboardingStateRequest), global::Onboardings.Domain.Queries.V2.GetEntityOnboardingStateRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Onboardings.Domain.Queries.V2.GetEntityOnboardingStateResponse), global::Onboardings.Domain.Queries.V2.GetEntityOnboardingStateResponse.Parser, new[]{ "Id", "Args", "Approval", "CurrentValue", "ApprovalTimeRemainingSeconds" }, new[]{ "ApprovalTimeRemainingSeconds" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetEntityOnboardingStateRequest : pb::IMessage<GetEntityOnboardingStateRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetEntityOnboardingStateRequest> _parser = new pb::MessageParser<GetEntityOnboardingStateRequest>(() => new GetEntityOnboardingStateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetEntityOnboardingStateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Onboardings.Domain.Queries.V2.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateRequest(GetEntityOnboardingStateRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateRequest Clone() {
      return new GetEntityOnboardingStateRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetEntityOnboardingStateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetEntityOnboardingStateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetEntityOnboardingStateRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetEntityOnboardingStateResponse : pb::IMessage<GetEntityOnboardingStateResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetEntityOnboardingStateResponse> _parser = new pb::MessageParser<GetEntityOnboardingStateResponse>(() => new GetEntityOnboardingStateResponse());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetEntityOnboardingStateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Onboardings.Domain.Queries.V2.MessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateResponse(GetEntityOnboardingStateResponse other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      args_ = other.args_ != null ? other.args_.Clone() : null;
      approval_ = other.approval_ != null ? other.approval_.Clone() : null;
      currentValue_ = other.currentValue_;
      approvalTimeRemainingSeconds_ = other.approvalTimeRemainingSeconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateResponse Clone() {
      return new GetEntityOnboardingStateResponse(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "args" field.</summary>
    public const int ArgsFieldNumber = 2;
    private global::Onboardings.Domain.Workflows.V2.OnboardEntityRequest args_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Onboardings.Domain.Workflows.V2.OnboardEntityRequest Args {
      get { return args_; }
      set {
        args_ = value;
      }
    }

    /// <summary>Field number for the "approval" field.</summary>
    public const int ApprovalFieldNumber = 3;
    private global::Onboardings.Domain.Values.V1.Approval approval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Onboardings.Domain.Values.V1.Approval Approval {
      get { return approval_; }
      set {
        approval_ = value;
      }
    }

    /// <summary>Field number for the "current_value" field.</summary>
    public const int CurrentValueFieldNumber = 4;
    private string currentValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CurrentValue {
      get { return currentValue_; }
      set {
        currentValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "approval_time_remaining_seconds" field.</summary>
    public const int ApprovalTimeRemainingSecondsFieldNumber = 5;
    private readonly static ulong ApprovalTimeRemainingSecondsDefaultValue = 0UL;

    private ulong approvalTimeRemainingSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ApprovalTimeRemainingSeconds {
      get { if ((_hasBits0 & 1) != 0) { return approvalTimeRemainingSeconds_; } else { return ApprovalTimeRemainingSecondsDefaultValue; } }
      set {
        _hasBits0 |= 1;
        approvalTimeRemainingSeconds_ = value;
      }
    }
    /// <summary>Gets whether the "approval_time_remaining_seconds" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasApprovalTimeRemainingSeconds {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "approval_time_remaining_seconds" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearApprovalTimeRemainingSeconds() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetEntityOnboardingStateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetEntityOnboardingStateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Args, other.Args)) return false;
      if (!object.Equals(Approval, other.Approval)) return false;
      if (CurrentValue != other.CurrentValue) return false;
      if (ApprovalTimeRemainingSeconds != other.ApprovalTimeRemainingSeconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (args_ != null) hash ^= Args.GetHashCode();
      if (approval_ != null) hash ^= Approval.GetHashCode();
      if (CurrentValue.Length != 0) hash ^= CurrentValue.GetHashCode();
      if (HasApprovalTimeRemainingSeconds) hash ^= ApprovalTimeRemainingSeconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (args_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Args);
      }
      if (approval_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Approval);
      }
      if (CurrentValue.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CurrentValue);
      }
      if (HasApprovalTimeRemainingSeconds) {
        output.WriteRawTag(40);
        output.WriteUInt64(ApprovalTimeRemainingSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (args_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Args);
      }
      if (approval_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Approval);
      }
      if (CurrentValue.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CurrentValue);
      }
      if (HasApprovalTimeRemainingSeconds) {
        output.WriteRawTag(40);
        output.WriteUInt64(ApprovalTimeRemainingSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (args_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Args);
      }
      if (approval_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Approval);
      }
      if (CurrentValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentValue);
      }
      if (HasApprovalTimeRemainingSeconds) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ApprovalTimeRemainingSeconds);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetEntityOnboardingStateResponse other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.args_ != null) {
        if (args_ == null) {
          Args = new global::Onboardings.Domain.Workflows.V2.OnboardEntityRequest();
        }
        Args.MergeFrom(other.Args);
      }
      if (other.approval_ != null) {
        if (approval_ == null) {
          Approval = new global::Onboardings.Domain.Values.V1.Approval();
        }
        Approval.MergeFrom(other.Approval);
      }
      if (other.CurrentValue.Length != 0) {
        CurrentValue = other.CurrentValue;
      }
      if (other.HasApprovalTimeRemainingSeconds) {
        ApprovalTimeRemainingSeconds = other.ApprovalTimeRemainingSeconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (args_ == null) {
              Args = new global::Onboardings.Domain.Workflows.V2.OnboardEntityRequest();
            }
            input.ReadMessage(Args);
            break;
          }
          case 26: {
            if (approval_ == null) {
              Approval = new global::Onboardings.Domain.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
          case 34: {
            CurrentValue = input.ReadString();
            break;
          }
          case 40: {
            ApprovalTimeRemainingSeconds = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (args_ == null) {
              Args = new global::Onboardings.Domain.Workflows.V2.OnboardEntityRequest();
            }
            input.ReadMessage(Args);
            break;
          }
          case 26: {
            if (approval_ == null) {
              Approval = new global::Onboardings.Domain.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
          case 34: {
            CurrentValue = input.ReadString();
            break;
          }
          case 40: {
            ApprovalTimeRemainingSeconds = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
