// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: onboardings/domain/queries/v2/message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Onboardings.Domain.Queries.V2 {

  /// <summary>Holder for reflection information generated from onboardings/domain/queries/v2/message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for onboardings/domain/queries/v2/message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitvbmJvYXJkaW5ncy9kb21haW4vcXVlcmllcy92Mi9tZXNzYWdlLnByb3Rv",
            "Eh1vbmJvYXJkaW5ncy5kb21haW4ucXVlcmllcy52Mhotb25ib2FyZGluZ3Mv",
            "ZG9tYWluL3dvcmtmbG93cy92Mi9tZXNzYWdlLnByb3RvGipvbmJvYXJkaW5n",
            "cy9kb21haW4vdmFsdWVzL3YxL21lc3NhZ2UucHJvdG8ilAIKHUVudGl0eU9u",
            "Ym9hcmRpbmdTdGF0ZVJlc3BvbnNlEg4KAmlkGAEgASgJUgJpZBJYCgxzZW50",
            "X3JlcXVlc3QYAiABKAsyNS5vbmJvYXJkaW5ncy5kb21haW4ud29ya2Zsb3dz",
            "LnYyLk9uYm9hcmRFbnRpdHlSZXF1ZXN0UgtzZW50UmVxdWVzdBJCCghhcHBy",
            "b3ZhbBgDIAEoCzImLm9uYm9hcmRpbmdzLmRvbWFpbi52YWx1ZXMudjEuQXBw",
            "cm92YWxSCGFwcHJvdmFsEkUKH2FwcHJvdmFsX3RpbWVfcmVtYWluaW5nX3Nl",
            "Y29uZHMYBCABKARSHGFwcHJvdmFsVGltZVJlbWFpbmluZ1NlY29uZHNCyAEK",
            "IWNvbS5vbmJvYXJkaW5ncy5kb21haW4ucXVlcmllcy52MkIMTWVzc2FnZVBy",
            "b3RvUAGiAgNPRFGqAh1PbmJvYXJkaW5ncy5Eb21haW4uUXVlcmllcy5WMsoC",
            "HU9uYm9hcmRpbmdzXERvbWFpblxRdWVyaWVzXFYy4gIpT25ib2FyZGluZ3Nc",
            "RG9tYWluXFF1ZXJpZXNcVjJcR1BCTWV0YWRhdGHqAiBPbmJvYXJkaW5nczo6",
            "RG9tYWluOjpRdWVyaWVzOjpWMmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Onboardings.Domain.Workflows.V2.MessageReflection.Descriptor, global::Onboardings.Domain.Values.V1.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Onboardings.Domain.Queries.V2.EntityOnboardingStateResponse), global::Onboardings.Domain.Queries.V2.EntityOnboardingStateResponse.Parser, new[]{ "Id", "SentRequest", "Approval", "ApprovalTimeRemainingSeconds" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EntityOnboardingStateResponse : pb::IMessage<EntityOnboardingStateResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityOnboardingStateResponse> _parser = new pb::MessageParser<EntityOnboardingStateResponse>(() => new EntityOnboardingStateResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityOnboardingStateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Onboardings.Domain.Queries.V2.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityOnboardingStateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityOnboardingStateResponse(EntityOnboardingStateResponse other) : this() {
      id_ = other.id_;
      sentRequest_ = other.sentRequest_ != null ? other.sentRequest_.Clone() : null;
      approval_ = other.approval_ != null ? other.approval_.Clone() : null;
      approvalTimeRemainingSeconds_ = other.approvalTimeRemainingSeconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityOnboardingStateResponse Clone() {
      return new EntityOnboardingStateResponse(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sent_request" field.</summary>
    public const int SentRequestFieldNumber = 2;
    private global::Onboardings.Domain.Workflows.V2.OnboardEntityRequest sentRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Onboardings.Domain.Workflows.V2.OnboardEntityRequest SentRequest {
      get { return sentRequest_; }
      set {
        sentRequest_ = value;
      }
    }

    /// <summary>Field number for the "approval" field.</summary>
    public const int ApprovalFieldNumber = 3;
    private global::Onboardings.Domain.Values.V1.Approval approval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Onboardings.Domain.Values.V1.Approval Approval {
      get { return approval_; }
      set {
        approval_ = value;
      }
    }

    /// <summary>Field number for the "approval_time_remaining_seconds" field.</summary>
    public const int ApprovalTimeRemainingSecondsFieldNumber = 4;
    private ulong approvalTimeRemainingSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ApprovalTimeRemainingSeconds {
      get { return approvalTimeRemainingSeconds_; }
      set {
        approvalTimeRemainingSeconds_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityOnboardingStateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityOnboardingStateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(SentRequest, other.SentRequest)) return false;
      if (!object.Equals(Approval, other.Approval)) return false;
      if (ApprovalTimeRemainingSeconds != other.ApprovalTimeRemainingSeconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (sentRequest_ != null) hash ^= SentRequest.GetHashCode();
      if (approval_ != null) hash ^= Approval.GetHashCode();
      if (ApprovalTimeRemainingSeconds != 0UL) hash ^= ApprovalTimeRemainingSeconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (sentRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SentRequest);
      }
      if (approval_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Approval);
      }
      if (ApprovalTimeRemainingSeconds != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(ApprovalTimeRemainingSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (sentRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SentRequest);
      }
      if (approval_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Approval);
      }
      if (ApprovalTimeRemainingSeconds != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(ApprovalTimeRemainingSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (sentRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SentRequest);
      }
      if (approval_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Approval);
      }
      if (ApprovalTimeRemainingSeconds != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ApprovalTimeRemainingSeconds);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityOnboardingStateResponse other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.sentRequest_ != null) {
        if (sentRequest_ == null) {
          SentRequest = new global::Onboardings.Domain.Workflows.V2.OnboardEntityRequest();
        }
        SentRequest.MergeFrom(other.SentRequest);
      }
      if (other.approval_ != null) {
        if (approval_ == null) {
          Approval = new global::Onboardings.Domain.Values.V1.Approval();
        }
        Approval.MergeFrom(other.Approval);
      }
      if (other.ApprovalTimeRemainingSeconds != 0UL) {
        ApprovalTimeRemainingSeconds = other.ApprovalTimeRemainingSeconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (sentRequest_ == null) {
              SentRequest = new global::Onboardings.Domain.Workflows.V2.OnboardEntityRequest();
            }
            input.ReadMessage(SentRequest);
            break;
          }
          case 26: {
            if (approval_ == null) {
              Approval = new global::Onboardings.Domain.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
          case 32: {
            ApprovalTimeRemainingSeconds = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (sentRequest_ == null) {
              SentRequest = new global::Onboardings.Domain.Workflows.V2.OnboardEntityRequest();
            }
            input.ReadMessage(SentRequest);
            break;
          }
          case 26: {
            if (approval_ == null) {
              Approval = new global::Onboardings.Domain.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
          case 32: {
            ApprovalTimeRemainingSeconds = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
