// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: jumpstart/api/onboardings/v1/message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Jumpstart.Api.Onboardings.V1 {

  /// <summary>Holder for reflection information generated from jumpstart/api/onboardings/v1/message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for jumpstart/api/onboardings/v1/message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipqdW1wc3RhcnQvYXBpL29uYm9hcmRpbmdzL3YxL21lc3NhZ2UucHJvdG8S",
            "HGp1bXBzdGFydC5hcGkub25ib2FyZGluZ3MudjEaLGp1bXBzdGFydC9kb21h",
            "aW4vb25ib2FyZGluZ3MvdjEvdmFsdWVzLnByb3RvImwKDEFwcHJvdmFsc1B1",
            "dBIOCgJpZBgBIAEoCVICaWQSTAoIYXBwcm92YWwYAiABKAsyMC5qdW1wc3Rh",
            "cnQuZG9tYWluLm9uYm9hcmRpbmdzLnZhbHVlcy52MS5BcHByb3ZhbFIIYXBw",
            "cm92YWwizAEKDk9uYm9hcmRpbmdzUHV0EhQKBXZhbHVlGAEgASgJUgV2YWx1",
            "ZRIvChBkZXB1dHlPd25lckVtYWlsGAIgASgJSABSEGRlcHV0eU93bmVyRW1h",
            "aWyIAQESUQoIYXBwcm92YWwYAyABKAsyMC5qdW1wc3RhcnQuZG9tYWluLm9u",
            "Ym9hcmRpbmdzLnZhbHVlcy52MS5BcHByb3ZhbEgBUghhcHByb3ZhbIgBAUIT",
            "ChFfZGVwdXR5T3duZXJFbWFpbEILCglfYXBwcm92YWwikwEKDk9uYm9hcmRp",
            "bmdzR2V0Eg4KAmlkGAEgASgJUgJpZBIjCg1jdXJyZW50X3ZhbHVlGAIgASgJ",
            "UgxjdXJyZW50VmFsdWUSTAoIYXBwcm92YWwYAyABKAsyMC5qdW1wc3RhcnQu",
            "ZG9tYWluLm9uYm9hcmRpbmdzLnZhbHVlcy52MS5BcHByb3ZhbFIIYXBwcm92",
            "YWxCwwEKIGNvbS5qdW1wc3RhcnQuYXBpLm9uYm9hcmRpbmdzLnYxQgxNZXNz",
            "YWdlUHJvdG9QAaICA0pBT6oCHEp1bXBzdGFydC5BcGkuT25ib2FyZGluZ3Mu",
            "VjHKAhxKdW1wc3RhcnRcQXBpXE9uYm9hcmRpbmdzXFYx4gIoSnVtcHN0YXJ0",
            "XEFwaVxPbmJvYXJkaW5nc1xWMVxHUEJNZXRhZGF0YeoCH0p1bXBzdGFydDo6",
            "QXBpOjpPbmJvYXJkaW5nczo6VjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Jumpstart.Domain.Onboardings.Values.V1.ValuesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Jumpstart.Api.Onboardings.V1.ApprovalsPut), global::Jumpstart.Api.Onboardings.V1.ApprovalsPut.Parser, new[]{ "Id", "Approval" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jumpstart.Api.Onboardings.V1.OnboardingsPut), global::Jumpstart.Api.Onboardings.V1.OnboardingsPut.Parser, new[]{ "Value", "DeputyOwnerEmail", "Approval" }, new[]{ "DeputyOwnerEmail", "Approval" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jumpstart.Api.Onboardings.V1.OnboardingsGet), global::Jumpstart.Api.Onboardings.V1.OnboardingsGet.Parser, new[]{ "Id", "CurrentValue", "Approval" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ApprovalsPut : pb::IMessage<ApprovalsPut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApprovalsPut> _parser = new pb::MessageParser<ApprovalsPut>(() => new ApprovalsPut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ApprovalsPut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jumpstart.Api.Onboardings.V1.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApprovalsPut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApprovalsPut(ApprovalsPut other) : this() {
      id_ = other.id_;
      approval_ = other.approval_ != null ? other.approval_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApprovalsPut Clone() {
      return new ApprovalsPut(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "approval" field.</summary>
    public const int ApprovalFieldNumber = 2;
    private global::Jumpstart.Domain.Onboardings.Values.V1.Approval approval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Jumpstart.Domain.Onboardings.Values.V1.Approval Approval {
      get { return approval_; }
      set {
        approval_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ApprovalsPut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ApprovalsPut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Approval, other.Approval)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (approval_ != null) hash ^= Approval.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (approval_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Approval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (approval_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Approval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (approval_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Approval);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ApprovalsPut other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.approval_ != null) {
        if (approval_ == null) {
          Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
        }
        Approval.MergeFrom(other.Approval);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (approval_ == null) {
              Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (approval_ == null) {
              Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OnboardingsPut : pb::IMessage<OnboardingsPut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OnboardingsPut> _parser = new pb::MessageParser<OnboardingsPut>(() => new OnboardingsPut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OnboardingsPut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jumpstart.Api.Onboardings.V1.MessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardingsPut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardingsPut(OnboardingsPut other) : this() {
      value_ = other.value_;
      deputyOwnerEmail_ = other.deputyOwnerEmail_;
      approval_ = other.approval_ != null ? other.approval_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardingsPut Clone() {
      return new OnboardingsPut(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private string value_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "deputyOwnerEmail" field.</summary>
    public const int DeputyOwnerEmailFieldNumber = 2;
    private readonly static string DeputyOwnerEmailDefaultValue = "";

    private string deputyOwnerEmail_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeputyOwnerEmail {
      get { return deputyOwnerEmail_ ?? DeputyOwnerEmailDefaultValue; }
      set {
        deputyOwnerEmail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "deputyOwnerEmail" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDeputyOwnerEmail {
      get { return deputyOwnerEmail_ != null; }
    }
    /// <summary>Clears the value of the "deputyOwnerEmail" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDeputyOwnerEmail() {
      deputyOwnerEmail_ = null;
    }

    /// <summary>Field number for the "approval" field.</summary>
    public const int ApprovalFieldNumber = 3;
    private global::Jumpstart.Domain.Onboardings.Values.V1.Approval approval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Jumpstart.Domain.Onboardings.Values.V1.Approval Approval {
      get { return approval_; }
      set {
        approval_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OnboardingsPut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OnboardingsPut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Value != other.Value) return false;
      if (DeputyOwnerEmail != other.DeputyOwnerEmail) return false;
      if (!object.Equals(Approval, other.Approval)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (HasDeputyOwnerEmail) hash ^= DeputyOwnerEmail.GetHashCode();
      if (approval_ != null) hash ^= Approval.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Value.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Value);
      }
      if (HasDeputyOwnerEmail) {
        output.WriteRawTag(18);
        output.WriteString(DeputyOwnerEmail);
      }
      if (approval_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Approval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Value.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Value);
      }
      if (HasDeputyOwnerEmail) {
        output.WriteRawTag(18);
        output.WriteString(DeputyOwnerEmail);
      }
      if (approval_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Approval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      if (HasDeputyOwnerEmail) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeputyOwnerEmail);
      }
      if (approval_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Approval);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OnboardingsPut other) {
      if (other == null) {
        return;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      if (other.HasDeputyOwnerEmail) {
        DeputyOwnerEmail = other.DeputyOwnerEmail;
      }
      if (other.approval_ != null) {
        if (approval_ == null) {
          Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
        }
        Approval.MergeFrom(other.Approval);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Value = input.ReadString();
            break;
          }
          case 18: {
            DeputyOwnerEmail = input.ReadString();
            break;
          }
          case 26: {
            if (approval_ == null) {
              Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Value = input.ReadString();
            break;
          }
          case 18: {
            DeputyOwnerEmail = input.ReadString();
            break;
          }
          case 26: {
            if (approval_ == null) {
              Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OnboardingsGet : pb::IMessage<OnboardingsGet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OnboardingsGet> _parser = new pb::MessageParser<OnboardingsGet>(() => new OnboardingsGet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OnboardingsGet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jumpstart.Api.Onboardings.V1.MessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardingsGet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardingsGet(OnboardingsGet other) : this() {
      id_ = other.id_;
      currentValue_ = other.currentValue_;
      approval_ = other.approval_ != null ? other.approval_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardingsGet Clone() {
      return new OnboardingsGet(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "current_value" field.</summary>
    public const int CurrentValueFieldNumber = 2;
    private string currentValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CurrentValue {
      get { return currentValue_; }
      set {
        currentValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "approval" field.</summary>
    public const int ApprovalFieldNumber = 3;
    private global::Jumpstart.Domain.Onboardings.Values.V1.Approval approval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Jumpstart.Domain.Onboardings.Values.V1.Approval Approval {
      get { return approval_; }
      set {
        approval_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OnboardingsGet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OnboardingsGet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (CurrentValue != other.CurrentValue) return false;
      if (!object.Equals(Approval, other.Approval)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (CurrentValue.Length != 0) hash ^= CurrentValue.GetHashCode();
      if (approval_ != null) hash ^= Approval.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (CurrentValue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CurrentValue);
      }
      if (approval_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Approval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (CurrentValue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CurrentValue);
      }
      if (approval_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Approval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (CurrentValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentValue);
      }
      if (approval_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Approval);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OnboardingsGet other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.CurrentValue.Length != 0) {
        CurrentValue = other.CurrentValue;
      }
      if (other.approval_ != null) {
        if (approval_ == null) {
          Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
        }
        Approval.MergeFrom(other.Approval);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            CurrentValue = input.ReadString();
            break;
          }
          case 26: {
            if (approval_ == null) {
              Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            CurrentValue = input.ReadString();
            break;
          }
          case 26: {
            if (approval_ == null) {
              Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
