// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: snailforce/api/v1/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Snailforce.Api.V1 {

  /// <summary>Holder for reflection information generated from snailforce/api/v1/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for snailforce/api/v1/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9zbmFpbGZvcmNlL2FwaS92MS9zZXJ2aWNlLnByb3RvEhFzbmFpbGZvcmNl",
            "LmFwaS52MRofc25haWxmb3JjZS9hcGkvdjEvbWVzc2FnZS5wcm90bzJoChFT",
            "bmFpbGZvcmNlU2VydmljZRJTCghSZWdpc3RlchIiLnNuYWlsZm9yY2UuYXBp",
            "LnYxLlJlZ2lzdGVyUmVxdWVzdBojLnNuYWlsZm9yY2UuYXBpLnYxLlJlZ2lz",
            "dGVyUmVzcG9uc2VCiwEKFWNvbS5zbmFpbGZvcmNlLmFwaS52MUIMU2Vydmlj",
            "ZVByb3RvUAGiAgNTQViqAhFTbmFpbGZvcmNlLkFwaS5WMcoCEVNuYWlsZm9y",
            "Y2VcQXBpXFYx4gIdU25haWxmb3JjZVxBcGlcVjFcR1BCTWV0YWRhdGHqAhNT",
            "bmFpbGZvcmNlOjpBcGk6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Snailforce.Api.V1.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
