// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: onboardings/domain/workflows/v1/message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Onboardings.Domain.Workflows.V1 {

  /// <summary>Holder for reflection information generated from onboardings/domain/workflows/v1/message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for onboardings/domain/workflows/v1/message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1vbmJvYXJkaW5ncy9kb21haW4vd29ya2Zsb3dzL3YxL21lc3NhZ2UucHJv",
            "dG8SH29uYm9hcmRpbmdzLmRvbWFpbi53b3JrZmxvd3MudjEaH2dvb2dsZS9w",
            "cm90b2J1Zi90aW1lc3RhbXAucHJvdG8ihwIKFE9uYm9hcmRFbnRpdHlSZXF1",
            "ZXN0EjgKCXRpbWVzdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1l",
            "c3RhbXBSCXRpbWVzdGFtcBIOCgJpZBgCIAEoCVICaWQSFAoFdmFsdWUYAyAB",
            "KAlSBXZhbHVlEjwKGmNvbXBsZXRpb25fdGltZW91dF9zZWNvbmRzGAQgASgE",
            "Uhhjb21wbGV0aW9uVGltZW91dFNlY29uZHMSLAoSZGVwdXR5X293bmVyX2Vt",
            "YWlsGAUgASgJUhBkZXB1dHlPd25lckVtYWlsEiMKDXNraXBfYXBwcm92YWwY",
            "BiABKAhSDHNraXBBcHByb3ZhbCp5CgZFcnJvcnMSIwofRVJST1JTX09OQk9B",
            "UkRfRU5USVRZX1RJTUVEX09VVBAAEiYKIkVSUk9SU19PTkJPQVJEX0VOVElU",
            "WV9JTlZBTElEX0FSR1MQARIiCh5FUlJPUlNfT05CT0FSRF9FTlRJVFlfUkVK",
            "RUNURUQQAkLSAQojY29tLm9uYm9hcmRpbmdzLmRvbWFpbi53b3JrZmxvd3Mu",
            "djFCDE1lc3NhZ2VQcm90b1ABogIDT0RXqgIfT25ib2FyZGluZ3MuRG9tYWlu",
            "LldvcmtmbG93cy5WMcoCH09uYm9hcmRpbmdzXERvbWFpblxXb3JrZmxvd3Nc",
            "VjHiAitPbmJvYXJkaW5nc1xEb21haW5cV29ya2Zsb3dzXFYxXEdQQk1ldGFk",
            "YXRh6gIiT25ib2FyZGluZ3M6OkRvbWFpbjo6V29ya2Zsb3dzOjpWMWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Onboardings.Domain.Workflows.V1.Errors), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Onboardings.Domain.Workflows.V1.OnboardEntityRequest), global::Onboardings.Domain.Workflows.V1.OnboardEntityRequest.Parser, new[]{ "Timestamp", "Id", "Value", "CompletionTimeoutSeconds", "DeputyOwnerEmail", "SkipApproval" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Errors {
    [pbr::OriginalName("ERRORS_ONBOARD_ENTITY_TIMED_OUT")] OnboardEntityTimedOut = 0,
    [pbr::OriginalName("ERRORS_ONBOARD_ENTITY_INVALID_ARGS")] OnboardEntityInvalidArgs = 1,
    [pbr::OriginalName("ERRORS_ONBOARD_ENTITY_REJECTED")] OnboardEntityRejected = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OnboardEntityRequest : pb::IMessage<OnboardEntityRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OnboardEntityRequest> _parser = new pb::MessageParser<OnboardEntityRequest>(() => new OnboardEntityRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OnboardEntityRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Onboardings.Domain.Workflows.V1.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardEntityRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardEntityRequest(OnboardEntityRequest other) : this() {
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      id_ = other.id_;
      value_ = other.value_;
      completionTimeoutSeconds_ = other.completionTimeoutSeconds_;
      deputyOwnerEmail_ = other.deputyOwnerEmail_;
      skipApproval_ = other.skipApproval_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnboardEntityRequest Clone() {
      return new OnboardEntityRequest(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private string value_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "completion_timeout_seconds" field.</summary>
    public const int CompletionTimeoutSecondsFieldNumber = 4;
    private ulong completionTimeoutSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CompletionTimeoutSeconds {
      get { return completionTimeoutSeconds_; }
      set {
        completionTimeoutSeconds_ = value;
      }
    }

    /// <summary>Field number for the "deputy_owner_email" field.</summary>
    public const int DeputyOwnerEmailFieldNumber = 5;
    private string deputyOwnerEmail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeputyOwnerEmail {
      get { return deputyOwnerEmail_; }
      set {
        deputyOwnerEmail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "skip_approval" field.</summary>
    public const int SkipApprovalFieldNumber = 6;
    private bool skipApproval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SkipApproval {
      get { return skipApproval_; }
      set {
        skipApproval_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OnboardEntityRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OnboardEntityRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (Id != other.Id) return false;
      if (Value != other.Value) return false;
      if (CompletionTimeoutSeconds != other.CompletionTimeoutSeconds) return false;
      if (DeputyOwnerEmail != other.DeputyOwnerEmail) return false;
      if (SkipApproval != other.SkipApproval) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (CompletionTimeoutSeconds != 0UL) hash ^= CompletionTimeoutSeconds.GetHashCode();
      if (DeputyOwnerEmail.Length != 0) hash ^= DeputyOwnerEmail.GetHashCode();
      if (SkipApproval != false) hash ^= SkipApproval.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Value);
      }
      if (CompletionTimeoutSeconds != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(CompletionTimeoutSeconds);
      }
      if (DeputyOwnerEmail.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DeputyOwnerEmail);
      }
      if (SkipApproval != false) {
        output.WriteRawTag(48);
        output.WriteBool(SkipApproval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Value);
      }
      if (CompletionTimeoutSeconds != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(CompletionTimeoutSeconds);
      }
      if (DeputyOwnerEmail.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DeputyOwnerEmail);
      }
      if (SkipApproval != false) {
        output.WriteRawTag(48);
        output.WriteBool(SkipApproval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      if (CompletionTimeoutSeconds != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CompletionTimeoutSeconds);
      }
      if (DeputyOwnerEmail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeputyOwnerEmail);
      }
      if (SkipApproval != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OnboardEntityRequest other) {
      if (other == null) {
        return;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      if (other.CompletionTimeoutSeconds != 0UL) {
        CompletionTimeoutSeconds = other.CompletionTimeoutSeconds;
      }
      if (other.DeputyOwnerEmail.Length != 0) {
        DeputyOwnerEmail = other.DeputyOwnerEmail;
      }
      if (other.SkipApproval != false) {
        SkipApproval = other.SkipApproval;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 26: {
            Value = input.ReadString();
            break;
          }
          case 32: {
            CompletionTimeoutSeconds = input.ReadUInt64();
            break;
          }
          case 42: {
            DeputyOwnerEmail = input.ReadString();
            break;
          }
          case 48: {
            SkipApproval = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 26: {
            Value = input.ReadString();
            break;
          }
          case 32: {
            CompletionTimeoutSeconds = input.ReadUInt64();
            break;
          }
          case 42: {
            DeputyOwnerEmail = input.ReadString();
            break;
          }
          case 48: {
            SkipApproval = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
