// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: jumpstart/domain/onboardings/v1/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Jumpstart.Domain.Onboardings.V1 {

  /// <summary>Holder for reflection information generated from jumpstart/domain/onboardings/v1/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for jumpstart/domain/onboardings/v1/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1qdW1wc3RhcnQvZG9tYWluL29uYm9hcmRpbmdzL3YxL3NlcnZpY2UucHJv",
            "dG8SH2p1bXBzdGFydC5kb21haW4ub25ib2FyZGluZ3MudjEaLmp1bXBzdGFy",
            "dC9kb21haW4vb25ib2FyZGluZ3MvdjEvY29tbWFuZHMucHJvdG8yhQEKEk9u",
            "Ym9hcmRpbmdzU2VydmljZRJvCghSZWdpc3RlchIwLmp1bXBzdGFydC5kb21h",
            "aW4ub25ib2FyZGluZ3MudjEuUmVnaXN0ZXJSZXF1ZXN0GjEuanVtcHN0YXJ0",
            "LmRvbWFpbi5vbmJvYXJkaW5ncy52MS5SZWdpc3RlclJlc3BvbnNlQtIBCiNj",
            "b20uanVtcHN0YXJ0LmRvbWFpbi5vbmJvYXJkaW5ncy52MUIMU2VydmljZVBy",
            "b3RvUAGiAgNKRE+qAh9KdW1wc3RhcnQuRG9tYWluLk9uYm9hcmRpbmdzLlYx",
            "ygIfSnVtcHN0YXJ0XERvbWFpblxPbmJvYXJkaW5nc1xWMeICK0p1bXBzdGFy",
            "dFxEb21haW5cT25ib2FyZGluZ3NcVjFcR1BCTWV0YWRhdGHqAiJKdW1wc3Rh",
            "cnQ6OkRvbWFpbjo6T25ib2FyZGluZ3M6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Jumpstart.Domain.Onboardings.V1.CommandsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
