@Temporal.Curriculum.Starters_HostAddress = http://localhost:5031
@id=onboarding-123

PUT {{Temporal.Curriculum.Starters_HostAddress}}/onboardings/{{id}}
Accept: application/json

{
"value": "required onboarding value"
}

###
