// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: jumpstart/domain/snailforce/v1/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Jumpstart.Domain.Snailforce.V1 {

  /// <summary>Holder for reflection information generated from jumpstart/domain/snailforce/v1/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for jumpstart/domain/snailforce/v1/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixqdW1wc3RhcnQvZG9tYWluL3NuYWlsZm9yY2UvdjEvc2VydmljZS5wcm90",
            "bxIeanVtcHN0YXJ0LmRvbWFpbi5zbmFpbGZvcmNlLnYxGixqdW1wc3RhcnQv",
            "ZG9tYWluL3NuYWlsZm9yY2UvdjEvbWVzc2FnZS5wcm90bzKCAQoRU25haWxm",
            "b3JjZVNlcnZpY2USbQoIUmVnaXN0ZXISLy5qdW1wc3RhcnQuZG9tYWluLnNu",
            "YWlsZm9yY2UudjEuUmVnaXN0ZXJSZXF1ZXN0GjAuanVtcHN0YXJ0LmRvbWFp",
            "bi5zbmFpbGZvcmNlLnYxLlJlZ2lzdGVyUmVzcG9uc2VCzQEKImNvbS5qdW1w",
            "c3RhcnQuZG9tYWluLnNuYWlsZm9yY2UudjFCDFNlcnZpY2VQcm90b1ABogID",
            "SkRTqgIeSnVtcHN0YXJ0LkRvbWFpbi5TbmFpbGZvcmNlLlYxygIeSnVtcHN0",
            "YXJ0XERvbWFpblxTbmFpbGZvcmNlXFYx4gIqSnVtcHN0YXJ0XERvbWFpblxT",
            "bmFpbGZvcmNlXFYxXEdQQk1ldGFkYXRh6gIhSnVtcHN0YXJ0OjpEb21haW46",
            "OlNuYWlsZm9yY2U6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Jumpstart.Domain.Snailforce.V1.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
