// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: jumpstart/domain/onboardings/v1/queries.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Jumpstart.Domain.Onboardings.Queries.V1 {

  /// <summary>Holder for reflection information generated from jumpstart/domain/onboardings/v1/queries.proto</summary>
  public static partial class QueriesReflection {

    #region Descriptor
    /// <summary>File descriptor for jumpstart/domain/onboardings/v1/queries.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QueriesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1qdW1wc3RhcnQvZG9tYWluL29uYm9hcmRpbmdzL3YxL3F1ZXJpZXMucHJv",
            "dG8SJ2p1bXBzdGFydC5kb21haW4ub25ib2FyZGluZ3MucXVlcmllcy52MRov",
            "anVtcHN0YXJ0L2RvbWFpbi9vbmJvYXJkaW5ncy92MS93b3JrZmxvd3MucHJv",
            "dG8aLGp1bXBzdGFydC9kb21haW4vb25ib2FyZGluZ3MvdjEvdmFsdWVzLnBy",
            "b3RvIiEKH0dldEVudGl0eU9uYm9hcmRpbmdTdGF0ZVJlcXVlc3Qi6gIKIEdl",
            "dEVudGl0eU9uYm9hcmRpbmdTdGF0ZVJlc3BvbnNlEg4KAmlkGAEgASgJUgJp",
            "ZBJTCgRhcmdzGAIgASgLMj8uanVtcHN0YXJ0LmRvbWFpbi5vbmJvYXJkaW5n",
            "cy53b3JrZmxvd3MudjEuT25ib2FyZEVudGl0eVJlcXVlc3RSBGFyZ3MSTAoI",
            "YXBwcm92YWwYAyABKAsyMC5qdW1wc3RhcnQuZG9tYWluLm9uYm9hcmRpbmdz",
            "LnZhbHVlcy52MS5BcHByb3ZhbFIIYXBwcm92YWwSIwoNY3VycmVudF92YWx1",
            "ZRgEIAEoCVIMY3VycmVudFZhbHVlEkoKH2FwcHJvdmFsX3RpbWVfcmVtYWlu",
            "aW5nX3NlY29uZHMYBSABKARIAFIcYXBwcm92YWxUaW1lUmVtYWluaW5nU2Vj",
            "b25kc4gBAUIiCiBfYXBwcm92YWxfdGltZV9yZW1haW5pbmdfc2Vjb25kc0L8",
            "AQorY29tLmp1bXBzdGFydC5kb21haW4ub25ib2FyZGluZ3MucXVlcmllcy52",
            "MUIMUXVlcmllc1Byb3RvUAGiAgRKRE9RqgInSnVtcHN0YXJ0LkRvbWFpbi5P",
            "bmJvYXJkaW5ncy5RdWVyaWVzLlYxygInSnVtcHN0YXJ0XERvbWFpblxPbmJv",
            "YXJkaW5nc1xRdWVyaWVzXFYx4gIzSnVtcHN0YXJ0XERvbWFpblxPbmJvYXJk",
            "aW5nc1xRdWVyaWVzXFYxXEdQQk1ldGFkYXRh6gIrSnVtcHN0YXJ0OjpEb21h",
            "aW46Ok9uYm9hcmRpbmdzOjpRdWVyaWVzOjpWMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Jumpstart.Domain.Onboardings.Workflows.V1.WorkflowsReflection.Descriptor, global::Jumpstart.Domain.Onboardings.Values.V1.ValuesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Jumpstart.Domain.Onboardings.Queries.V1.GetEntityOnboardingStateRequest), global::Jumpstart.Domain.Onboardings.Queries.V1.GetEntityOnboardingStateRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jumpstart.Domain.Onboardings.Queries.V1.GetEntityOnboardingStateResponse), global::Jumpstart.Domain.Onboardings.Queries.V1.GetEntityOnboardingStateResponse.Parser, new[]{ "Id", "Args", "Approval", "CurrentValue", "ApprovalTimeRemainingSeconds" }, new[]{ "ApprovalTimeRemainingSeconds" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetEntityOnboardingStateRequest : pb::IMessage<GetEntityOnboardingStateRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetEntityOnboardingStateRequest> _parser = new pb::MessageParser<GetEntityOnboardingStateRequest>(() => new GetEntityOnboardingStateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetEntityOnboardingStateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jumpstart.Domain.Onboardings.Queries.V1.QueriesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateRequest(GetEntityOnboardingStateRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateRequest Clone() {
      return new GetEntityOnboardingStateRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetEntityOnboardingStateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetEntityOnboardingStateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetEntityOnboardingStateRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetEntityOnboardingStateResponse : pb::IMessage<GetEntityOnboardingStateResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetEntityOnboardingStateResponse> _parser = new pb::MessageParser<GetEntityOnboardingStateResponse>(() => new GetEntityOnboardingStateResponse());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetEntityOnboardingStateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jumpstart.Domain.Onboardings.Queries.V1.QueriesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateResponse(GetEntityOnboardingStateResponse other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      args_ = other.args_ != null ? other.args_.Clone() : null;
      approval_ = other.approval_ != null ? other.approval_.Clone() : null;
      currentValue_ = other.currentValue_;
      approvalTimeRemainingSeconds_ = other.approvalTimeRemainingSeconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetEntityOnboardingStateResponse Clone() {
      return new GetEntityOnboardingStateResponse(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "args" field.</summary>
    public const int ArgsFieldNumber = 2;
    private global::Jumpstart.Domain.Onboardings.Workflows.V1.OnboardEntityRequest args_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Jumpstart.Domain.Onboardings.Workflows.V1.OnboardEntityRequest Args {
      get { return args_; }
      set {
        args_ = value;
      }
    }

    /// <summary>Field number for the "approval" field.</summary>
    public const int ApprovalFieldNumber = 3;
    private global::Jumpstart.Domain.Onboardings.Values.V1.Approval approval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Jumpstart.Domain.Onboardings.Values.V1.Approval Approval {
      get { return approval_; }
      set {
        approval_ = value;
      }
    }

    /// <summary>Field number for the "current_value" field.</summary>
    public const int CurrentValueFieldNumber = 4;
    private string currentValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CurrentValue {
      get { return currentValue_; }
      set {
        currentValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "approval_time_remaining_seconds" field.</summary>
    public const int ApprovalTimeRemainingSecondsFieldNumber = 5;
    private readonly static ulong ApprovalTimeRemainingSecondsDefaultValue = 0UL;

    private ulong approvalTimeRemainingSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ApprovalTimeRemainingSeconds {
      get { if ((_hasBits0 & 1) != 0) { return approvalTimeRemainingSeconds_; } else { return ApprovalTimeRemainingSecondsDefaultValue; } }
      set {
        _hasBits0 |= 1;
        approvalTimeRemainingSeconds_ = value;
      }
    }
    /// <summary>Gets whether the "approval_time_remaining_seconds" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasApprovalTimeRemainingSeconds {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "approval_time_remaining_seconds" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearApprovalTimeRemainingSeconds() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetEntityOnboardingStateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetEntityOnboardingStateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Args, other.Args)) return false;
      if (!object.Equals(Approval, other.Approval)) return false;
      if (CurrentValue != other.CurrentValue) return false;
      if (ApprovalTimeRemainingSeconds != other.ApprovalTimeRemainingSeconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (args_ != null) hash ^= Args.GetHashCode();
      if (approval_ != null) hash ^= Approval.GetHashCode();
      if (CurrentValue.Length != 0) hash ^= CurrentValue.GetHashCode();
      if (HasApprovalTimeRemainingSeconds) hash ^= ApprovalTimeRemainingSeconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (args_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Args);
      }
      if (approval_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Approval);
      }
      if (CurrentValue.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CurrentValue);
      }
      if (HasApprovalTimeRemainingSeconds) {
        output.WriteRawTag(40);
        output.WriteUInt64(ApprovalTimeRemainingSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (args_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Args);
      }
      if (approval_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Approval);
      }
      if (CurrentValue.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CurrentValue);
      }
      if (HasApprovalTimeRemainingSeconds) {
        output.WriteRawTag(40);
        output.WriteUInt64(ApprovalTimeRemainingSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (args_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Args);
      }
      if (approval_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Approval);
      }
      if (CurrentValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentValue);
      }
      if (HasApprovalTimeRemainingSeconds) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ApprovalTimeRemainingSeconds);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetEntityOnboardingStateResponse other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.args_ != null) {
        if (args_ == null) {
          Args = new global::Jumpstart.Domain.Onboardings.Workflows.V1.OnboardEntityRequest();
        }
        Args.MergeFrom(other.Args);
      }
      if (other.approval_ != null) {
        if (approval_ == null) {
          Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
        }
        Approval.MergeFrom(other.Approval);
      }
      if (other.CurrentValue.Length != 0) {
        CurrentValue = other.CurrentValue;
      }
      if (other.HasApprovalTimeRemainingSeconds) {
        ApprovalTimeRemainingSeconds = other.ApprovalTimeRemainingSeconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (args_ == null) {
              Args = new global::Jumpstart.Domain.Onboardings.Workflows.V1.OnboardEntityRequest();
            }
            input.ReadMessage(Args);
            break;
          }
          case 26: {
            if (approval_ == null) {
              Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
          case 34: {
            CurrentValue = input.ReadString();
            break;
          }
          case 40: {
            ApprovalTimeRemainingSeconds = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (args_ == null) {
              Args = new global::Jumpstart.Domain.Onboardings.Workflows.V1.OnboardEntityRequest();
            }
            input.ReadMessage(Args);
            break;
          }
          case 26: {
            if (approval_ == null) {
              Approval = new global::Jumpstart.Domain.Onboardings.Values.V1.Approval();
            }
            input.ReadMessage(Approval);
            break;
          }
          case 34: {
            CurrentValue = input.ReadString();
            break;
          }
          case 40: {
            ApprovalTimeRemainingSeconds = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
