<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.31.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
        <PackageReference Include="Temporalio" Version="1.8.0" />
      <PackageReference Include="Temporalio.Extensions.Hosting" Version="1.8.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\App.Generated\App.Generated.csproj" />
    </ItemGroup>

</Project>
